apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: source
spec:
  params:
  - name: clone
    type: string
    description: Git repository to be cloned
    default: https://gitee.com/mageedu/spring-boot-helloWorld.git
  workspaces:
  - name: source
  steps:
  - name: git-clone
    image: alpine:3.15
    script: |
      #!/bin/sh
      apk add -q git && echo "git installed ..."
      git clone -v $(params.repo) $(workspaces.source.path)/source
---

