apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helloworld
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - environment: dev
      - environment: staging
      - environment: prod
  template:
    metadata:
      name: '{{environment}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://gitee.com/mageedu/spring-boot-helloworld-deployment.git
        targetRevision: HEAD
        path: helloworld/{{environment}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{environment}}'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - Validate=false
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
  syncPolicy:
    preserveResourcesOnDeletion: false
